language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - apt-get install python-pip python-dev build-essential
  - pip install --upgrade pip
  - pip install awscli --upgrade

script: ./travis-script.sh
