sudo: required

language: java

jdk:
  - oraclejdk10

python:
  - 3.4

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python-pip python-dev build-essential
  - sudo -H pip install --upgrade --force-reinstall pip==9.0.3
  - sudo -H pip install awscli --upgrade
  - sudo -H pip install dxpy --upgrade
  - mkdir ~/.aws
  - printf "[genetraps]\naws_access_key_id="$AWS_ACCESS_KEY_ID"\naws_secret_access_key="$AWS_SECRET_ACCESS_KEY > ~/.aws/credentials
  - printf "[profile genetraps]\nregion="$AWS_REGION"\noutput=json" > ~/.aws/config
  - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - sudo chmod a+x /usr/local/bin/ecs-cli

script: ./travis-script.sh
